CREATE TABLE IF NOT EXISTS PAYMENT
(
    id   NUMBER(19) GENERATED ALWAYS AS IDENTITY,
    status VARCHAR2(7) NOT NULL,
    trackingCode  VARCHAR2(32) NOT NULL,
    reference  VARCHAR2(32) NOT NULL,
    createdAt  TIMESTAMP(6),
    updatedAt  TIMESTAMP(6),
    CONSTRAINT UC_PAYMENT UNIQUE (id),
);


CREATE TABLE IF NOT EXISTS CONTRADICTION
(
    id   NUMBER(19) GENERATED ALWAYS AS IDENTITY,
    reference VARCHAR2(7) NOT NULL,
    amount  NUMBER(19) NOT NULL,
    destinationAccount  VARCHAR2(32) NOT NULL,
    createdAt  TIMESTAMP(6),
    updatedAt  TIMESTAMP(6),
    CONSTRAINT UC_CONTRADICTION UNIQUE (id),
);
